spring.application.name=final

# MySQL
spring.datasource.url=jdbc:mysql://localhost:3306/rutaIA
spring.datasource.username=root
spring.datasource.password=200609
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA
spring.jpa.hibernate.ddl-auto=none
spring.jpa.open-in-view=false

# n8n webhooks
rutaia.n8n.sync-webhook-url=https://structure-various-bonding.ngrok-free.dev/webhook-test/curso-sync
rutaia.n8n.query-webhook-url=https://structure-various-bonding.ngrok-free.dev/webhook-test/3801bc45-56eb-44b5-bbf1-ff4bbfe3520a
rutaia.n8n.webhook-secret=${N8N_WEBHOOK_SECRET}

# CORS
rutaia.cors.allowed-origins=http://localhost:3000,http://127.0.0.1:3000